# Generated by Django 5.0.1 on 2024-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='surname',
            field=models.CharField(default='guggilam', max_length=45),
        ),
    ]
