# Generated by Django 2.1.7 on 2024-07-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
