# Generated by Django 2.1.7 on 2024-07-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('poster', models.ImageField(upload_to='')),
                ('cast', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=100)),
                ('zoner', models.CharField(max_length=250)),
            ],
        ),
    ]
